update travis config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,29 +4,64 @@ dist: trusty
 env:  
   - CLI_VERSION=latest
 addons:  
-apt:
-  packages:
-  - gettext
-  - libcurl4-openssl-dev
-  - libicu-dev
-  - libssl-dev
-  - libunwind8
-  - zlib1g
-mono:  
-  - 4.2.3
-os:  
-  - linux
-  - osx
-osx_image: xcode7.1  
-branches:  
-  only:
-    - master
-before_install:  
-  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; brew link --force openssl; fi
-install:  
+  apt:
+    packages:
+    - gettext
+    - libcurl4-openssl-dev
+    - libicu-dev
+    - libssl-dev
+    - libunwind8
+    - zlib1g
+
+matrix:
+  include:
+    - os: linux
+      dist: trusty # Ubuntu 14.04
+      sudo: required
+      env: CONFIGURATION=Debug
+    - os: linux
+      dist: trusty
+      sudo: required
+      env: CONFIGURATION=Release
+    - os: osx
+      osx_image: xcode7.2 # macOS 10.11
+      env: CONFIGURATION=Debug
+    - os: osx
+      osx_image: xcode7.2
+      env: CONFIGURATION=Release
+
+before_install:
+  # Install OpenSSL
+  - if test "$TRAVIS_OS_NAME" == "osx"; then
+      brew update;
+      brew install openssl;
+      brew link --force openssl;
+      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=809128";
+    else
+      export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=809129";
+    fi
+
   - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
-  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
-  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  
+
+  # Install .NET CLI
+  - mkdir $DOTNET_INSTALL_DIR
+  - curl -L $DOTNET_SDK_URL -o dotnet_package
+  - tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR
+
+  # Add dotnet to PATH
+  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
+
+install:
+  # Display dotnet version info
+  - which dotnet;
+    if [ $? -eq 0 ]; then
+      echo "Using dotnet:";
+      dotnet --info;
+    else
+      echo "dotnet.exe not found"
+      exit 1;
+    fi
+    
 script:  
   - dotnet restore Candy.Core Candy.Core.Tests
   - dotnet build Candy.Core Candy.Core.Tests
